// <auto-generated />
namespace SocialPhotoEditor.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeFolder4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeFolder4));
        
        string IMigrationMetadata.Id
        {
            get { return "201705040919316_changeFolder4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
