// <auto-generated />
namespace SocialPhotoEditor.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reorganizeDB_version24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reorganizeDB_version24));
        
        string IMigrationMetadata.Id
        {
            get { return "201705190843340_reorganizeDB_version24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
